# payment-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1  # Number of replicas (pods) to deploy
  selector:
    matchLabels:
      app: payment-service  # Label to identify the pods
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: payment-service:latest  # The Docker image to use
        ports:
        - containerPort: 8081  # The port your service listens on
