# payment-notification-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-notification-service
  template:
    metadata:
      labels:
        app: payment-notification-service
    spec:
      containers:
      - name: payment-notification-service
        image: payment-notification-service:latest
        ports:
        - containerPort: 3001
